= Бизнес-процессы

Приложение добавляет в систему {dv} бизнес-процессы:

. _{ow} -- Автозавершение дочерних резолюций_.
+
БП завершения всех дочерних резолюций вниз по дереву резолюций при завершении родительского задания. Запускается при переводе задания в состояние Завершено.
+
. _{ow} -- Автозавершение родительского задания_.
+
БП завершения задания при завершении созданной из него резолюции. Запускается при переводе резолюции в состояние `Завершено`.
+
.Процесс выполняет следующие действия:
* Получает родительское задание.
* Проверяет, есть ли у задания дочерние резолюции, чье состояние отлично от `Завершено`.
* Если так резолюций нет, то задание завершается, при этом:
** В поле `Отчет` добавляются отчеты из подчиненных заданий первого уровня при соблюдении условий:
*** В _Справочнике видов карточек_ в настройках карточки резолюции установлен флаг `*Добавлять отчет в родительское задание*`.
*** В таблице исполнителей карточки резолюции в колонке _Отчет_ для данного задания установлена опция `*Текстовый*` или `*Требуется документ во исполнение*`.
** Копируется ссылка на документ во исполнение из подчиненных заданий первого уровня при соблюдении условий:
*** В таблице исполнителей карточки резолюции в колонке Отчет для данного задания установлена опция `*Требуется документ во исполнение*`.
*** Тип ссылки, с которой прикреплен документ, совпадает с указанным для карточки резолюции в Справочнике видов карточек в поле _Тип ссылки_ документа во исполнение.
+
. _{ow} -- Автозавершение родительской резолюции_.
+
БП завершения резолюции при завершении всех ее пунктов. Запускается при переводе карточки группа заданий, соответствующей какому-либо пункту резолюции, в состояние "Завершено". Процесс выполняет следующие действия:
* Получает родительскую резолюцию.
* Проверяет, все ли пункты этой резолюции завершены.
* Если да, завершает резолюцию (переводит в состояние Завершена).
+
. _{ow} -- Запуск резолюции_.
+
БП запуска резолюции на исполнение. Он запускается при переходе резолюции в состояние "Исполняется". Процесс выполняет следующие действия:
* Получает карточку резолюции.
* По каждому из пунктов резолюции формирует карточку группы заданий, в которую вносятся все сведения о пункте (список исполнителей, ответственный, сроки исполнения, текст резолюции и т. д).
* Каждая из карточек группы заданий рассылает задания исполнителям согласно листу исполнения.
+
. _{ow} -- Изменение состояния родительского документа_.
+
БП изменения состояния отправленного на рассмотрение родительского документа при выборе в соответствующем дочернем задании вида На рассмотрение варианта завершения Документ в архив или Документ исполнен. Запускается при переходе задания вида На рассмотрение в состояние "Завершено". Процесс выполняет следующие действия:
* Получает карточку родительского документа. Если таковая отсутствует, бизнес-процесс завершается.
* Переводит карточку родительского документа в одно из состояний:
** Исполнен, если дочернее задание было завершено по кнопке *Документ исполнен*.
** В архиве, если дочернее задание было завершено по кнопке *Документ в архив*.
* После завершения работы экземпляр бизнес-процесса удаляется.
+
. _{ow} -- Отзыв резолюций_.
+
БП отзыва резолюции. Запускается при нажатии в карточке резолюции кнопки *Отозвать* и подтверждении этого действия. Процесс выполняет следующие действия:
* Получает родительскую резолюцию.
* Проверяет, все ли пункты этой резолюции завершены.
* Если нет, отзывает задания незавершенных пунктов (переводит в состояние Отозвано).
+
. _{ow} -- Отзыв дочерних резолюций_.
+
БП отзыва дочерних резолюций при отзыве или завершении родительской резолюции. Запускается при нажатии в карточке родительской резолюции кнопки *Отозвать* и подтверждении этого действия. Процесс выполняет следующие действия:
* Получает родительскую резолюцию.
* Проверяет, все ли пункты этой резолюции завершены.
* Если нет, проверяет, есть ли у незавершенных заданий незавершенные дочерние резолюции.
* Находит незавершенные пункты дочерних резолюций.
* Отзывает незавершенные задания незавершенных пунктов (переводит в состояние Отозвано).
+
. _{ow} -- Отзыв заданий ГЗ_.
+
БП отзыва заданий при отзыве группы заданий. Запускается при нажатии в карточке резолюции кнопки *Отозвать* и подтверждении этого действия.
