= Папки для работы с отчетами

Для работы с отчетами предназначена группа папок Отчеты, доступная всем пользователям. Папки данной группы предназначены для отображения сведений о работе пользователя. В стандартной поставке Приложения настроено использование отчетов _Исполнение документов_, _Исполнение резолюций_ и _Исполнение заданий_.

.Папки для работы с отчётами:
* `Исполнение документов`.
+
В папке отображаются карточки _ДокументДП_ в состояниях `На рассмотрении`, `Зарегистрирован`, `На исполнении`, удовлетворяющие следующим критериям параметрического поиска:
+
** Период, в который был зарегистрирован документ.
** Автор.
** Вид документа.
** Подразделение.
+
Карточки группируются по состоянию.
+
* `Исполнение заданий`.
+
В папке отображаются незавершенные задания, удовлетворяющие следующим критериям параметрического поиска:
+
** Исполнитель.
** Подразделение исполнителя.
** Вид задания.
** Срок исполнения.
+
Карточки группируются по исполнителям заданий. Просроченные задания выделяются красным цветом.
+
* `Исполнение резолюций`.
+
В папке отображаются карточки _Резолюция_ в состоянии `На исполнении`, удовлетворяющие следующим критериям параметрического поиска:
+
** Период, в который была создана Резолюция.
** Автор.
** Подразделение.
