= Папки для работы с карточками Резолюция

Для работы с резолюциями предназначена группа папок `Резолюции`, доступная всем пользователям Приложения.

Верхняя папка группы предназначена для создания карточек инициативной _Резолюции_.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек _Резолюция_ в различных состояниях по различным атрибутам.

.Папки для работы с карточками "Резолюция":
* `Завершенные в течение года`.
+
В папке отображаются карточки _Резолюция_ в состоянии Завершена, если завершение произошло в течение года.
* `Поиск резолюций`.
+
В папке отображаются карточки _Резолюция_, удовлетворяющие следующим критериям параметрического поиска:
+
** Состояние.
** Номер.
** Автор.
** Подготовил.
** Дата создания, интервал.
** Название.
** Название пункта.
** Исполнители.
** Общий срок исполнения, интервал.
** Контролёр.
** Дата контроля, интервал.
+
Карточки группируются по состоянию.
+
* `Резолюции на исполнении`.
+
В папке отображаются карточки _Резолюция_ в состоянии `На исполнении`.
+
Карточки группируются по резолюции.
