= Общие сведения о модуле

Приложение "{ow}" добавляет в систему "{dv} 5.5" (далее -- "{dv}") возможность автоматизации базовых процессов делопроизводства организации.

"{dv} 5. {ow}" является дополнительным модулем системы "{dv} 5.5", предназначенным для автоматизации базовых процессов делопроизводства организации -- регистрации и организации исполнения официальных документов в соответствии с российскими практиками ДОУ (документационного обеспечения управления).

Приложение представляет собой готовое к использованию прикладное решение по работе с документами, которое ориентировано на массовое использование -- повседневную работу сотрудников и их взаимодействие в составе рабочих групп. Может использоваться, когда требуется регистрация и исполнение документов по правилам классического делопроизводства (например, в госорганах, корпорациях государственного типа, крупных организациях с административным стилем управления и т. п).

.Приложение обеспечивает выполнение основных элементов классического делопроизводства:
* Регистрация, хранение, поиск и исполнение электронных документов.
* Классификация.
* Ознакомление.
* Работа с заданиями.

Приложение может быть модифицировано под нужды конкретного предприятия. Ограничения модификации приведены в разделе "xref:ROOT:restrictions.adoc[]".

[#purpose]
== Назначение документации

Настоящий раздел документации посвящён описанию приложения _{dv} 5. {ow}_.

Документация содержит инструкцию по установке, первоначальной настройке серверной и клиентской частей приложения, а также руководство пользователя приложения.

[#structure]
== Как организована документация

.Документация приложения содержит следующие разделы:
. xref:index.adoc[Общие сведения] -- раздел содержит общие сведения о Приложении, требования к подготовке пользователей, составные части Приложения и назначение документации.
. xref:admin:install.adoc[Установка и настройка] -- инструкция по установке Приложения.
. xref:admin:admin-functions.adoc[Функции администратора] -- описание настроек Приложения, выполняемых администратором {dv}.
. xref:user:Preparationfor_work.adoc[Подготовка к работе] -- условия для работы с карточками Модуля в программе {wincl}/РМА).
. xref:user:Folder_Application_OfficeWork.adoc[Папки приложения] -- описание папок Приложения.
. xref:user:Description_Fields_and_Buttons.adoc[Описание интерфейса карточек Приложения] -- приведено описание пользовательского интерфейса карточек ДокументДП, Резолюция, заданий По резолюции и На рассмотрение, Справочника номенклатуры дел 5 и карточки Дело.
. xref:user:Operations.adoc[Описание операций] -- описание основных операций с документами, резолюциями и заданиями Приложения, а также со Справочником номенклатуры дел 5.
