= Структура Приложения

Приложение "{ow}" состоит из двух частей:

. Серверная часть устанавливается на компьютер с сервером {dv} включает следующие элементы:
.. Схемы метаданных типов карточек:
+
* Карточка _Резолюция_ предназначена для формирования, рассылки и учета выданных заданий и контроля их исполнения. Каждая резолюция может состоять из нескольких пунктов, по каждому пункту может быть указано несколько исполнителей.
* Карточка _Дело_ предназначена для хранения сведений о деле Справочника номенклатуры дел 5;
* _Справочник номенклатуры дел 5_ предназначен для регистрации места хранения бумажных документов, а также для классификации документов организации.
+
.. Загружаемые в систему {dv} данные: xref:card-kinds.adoc[виды карточек], xref:roles.adoc[роли], xref:folders.adoc[папки], xref:groups.adoc[группы сотрудников], xref:business-processes.adoc[бизнес-процессы], скрипты карточек.
.. Пакет установки клиентской части приложения _{ow}_.
. Клиентская часть устанавливается на компьютеры пользователей {dv} включает следующие элементы:
.. Библиотеки DLL с компонентом библиотеки карточек, элементами пользовательского интерфейса карточек Приложения для Windows-клиента и РМА.
