= Сравнение возможностей приложений "{ow}" и "{dm}"

Система {dv} в базовом варианте содержит встроенное приложение "{dm}", в котором основные элементы классического делопроизводства реализованы в упрощенном виде.

Приложение "Делопроизводство. Версия 5" позволяет реализовать полнофункциональную канцелярскую работу, предоставляя описанные ниже возможности.

* Настроен вид карточки _Документ -- ДокументДП_ и дочерние виды _Входящий_, _Исходящий_, _Информационно-справочный_, _Организационный_ и _Распорядительный_.
** Расширенный набор атрибутов позволяет указать все сведения о документе.
** Сценарии приложения предусматривают рассылку заданий:
*** _На рассмотрение -- задание_, используемое для доставки сотруднику документа для рассмотрения и предполагающее создание резолюции по документу;
*** _На ознакомление -- задание на ознакомление с документом_. При рассылке задания могут использоваться списки рассылки.
** Предусмотрены состояния документа, отражающие стадию его исполнения.
** Предусмотрена возможность согласования документа.
** Предусмотрена возможность шифрования файлов документа.
* Удобная регистрация документа в системе:
** Отдельно выделяется процедура регистрации. Настроена роль Делопроизводитель, предназначенная для регистрации документов и перевода их в архив.
** С момента создания карточки документа и до регистрации документу выделяется временный номер, что позволяет отслеживать движение незарегистрированного документа.
* Удобная обработка исходящей корреспонденции:
** Возможна печать конвертов и файлов исходящего документа для всех указанных в нем адресатов.
** Формируется реестр отправленных адресатам исходящих документов в двух видах: по стандартной для реестра заказной почтовой корреспонденции форме 103 и по форме списка. Форма список предназначена для импорта данных о регистрируемых почтовых отправлениях в программу "Партионная почта", предоставляемую Почтой России.
* Реализованы сценарии исполнения документов, для чего разработана карточка Резолюция.
** Резолюция может состоять из нескольких пунктов, по каждому из которых рассылаются задания исполнителям.
** Возможен отзыв резолюции, изменение сроков у пункта резолюции, добавление пункта резолюции, замена исполнителя, изменение текста поручения по пункту резолюции, постановка/снятие с контроля.
** Возможно утверждение резолюции.
** Возможна печать бланка резолюции для передачи должностному лицу, не работающему в СЭД.
** Возможен просмотр документов _Во исполнение_ заданий из карточки исходного документа.
** Формируется дерево резолюций, в котором отображаются пункты исходной резолюции и подчиненные резолюции.
** Разработаны две формы карточки Резолюция: редактируемая, предназначенная для указания и редактирования атрибутов резолюции, и форма для чтения, предназначенная для пользователей, не имеющих необходимости в редактировании атрибутов резолюции или пользователей, которым такие изменения не разрешены.
* Реализован контроль документов, заданий и резолюций.
** Предусмотрен контроль исполнения документа.
** Предусмотрен контроль хода исполнения заданий пункта резолюции.
** Предусмотрены два вида приемки заданий пункта резолюции: контроль организации и контроль подразделения.
** Реализовано создание документа _Во исполнение_ задания по резолюции.
** Разработаны отчеты для контроля исполнения документов, заданий и резолюций.
* Обработка бумажных документов.
** Разработан Справочник номенклатуры дел 5, в котором указываются места физического хранения бумажных документов организации.
** Введен журнал приема-передачи документов.

Подробное сравнение функциональности приложения "Делопроизводство. Версия 5" и приложения "{dm}" приведено ниже.

. Набор документов и состав атрибутов документов
+
* УД ({dm}). Упрощенный.
* ДП ({ow}). Расширенный.
+
. Наличие Регистратора.
+
* УД. Все сценарии предполагают, что автор самостоятельно работает в системе.
* ДП. Различаются роли "Автора" и "Регистратора" документа. Сценарии реализованы с учетом участия специального подразделения, выполняющего функции регистрации (Делопроизводители).
+
. Регистрация документа.
+
* УД. Ручное выделение постоянного номера. Регистрацию выполняет "Автор" документа.
* ДП. С автоматическим выделением временного номера "Регистрацию" выполняет "Делопроизводитель". Предусмотрена автоматическая регистрация. Предусмотрен атрибут "Место" регистрации.
+
. Контроль уникальности регистрируемых документов.
+
* УД. Отсутствует.
* ДП. Реализован контроль уникальности по атрибутам, набор которых атрибутов настраивается для вида документа.
+
. Доставка документов получателям.
+
* УД. Документы доставляются в специально настроенные папки получателям, указанным в карточке документа, задания для рассылки не используются.
* ДП. Рассылаются задания на рассмотрение и на ознакомление, при этом могут использоваться списки рассылки. Различаются "Адресаты" и "Получатели".
+
. Рассылка на ознакомление.
+
* УД. Вручную выбираются сотрудники для ознакомления.
* ДП. Возможно использование списков рассылки.
+
. Рассмотрение документов.
+
* УД. Получатель документа может создать произвольное задание или группу заданий.
* ДП. Предусмотрен сценарий расписывания резолюции.
+
. Исполнение документов.
+
* УД. Не предусмотрено.
* ДП. Реализованы сценарии исполнения документов с использованием механизма резолюций. Предусмотрены состояния документов, отражающие стадию его исполнения.
+
. Использование резолюций.
+
* УД. Возможно использование групп заданий без возможности создать подчиненную группу заданий.
* ДП. Реализован объект "Резолюция", состоящая из нескольких пунктов. По каждому пункту назначается ответственный и контроль. Возможно создание подчиненных резолюций из задания.
+
. Справочник текстов поручений.
+
* УД. Не предусмотрено.
* ДП. Реализован справочник текстов резолюций с возможностью автоподстановки.
+
. Дерево исполнений.
+
* УД. Формируется дерево заданий.
* ДП. Формируется дерево резолюций, в котором отображаются пункты исходной резолюции и подчиненные резолюции.
+
. Связывание документов.
+
* УД. Реализованы сценарии создания документов _В ответ на_ с переносом атрибутов.
* ДП. Дополнительно реализовано создание документов "На основании", автоматическое связывание документов _Во исполнение_ задания с основным документом.
+
. Согласование документов.
+
* УД. Можно настроить маршруты согласования любой сложности.
* ДП. Можно настроить маршруты согласования любой сложности.
+
. Учет движения бумажных экземпляров документов "Отсутствует". Разработан журнал приема/передачи документов, отображающий, в том числе, передачу группы документов по реестру.
. Списание в дело.
+
* УД. Отсутствует.
* ДП. Разработан справочник номенклатуры дел. Для документа предусмотрен атрибут "Индекс номенклатуры дел".
+
. Рассылка исходящих.
+
* УД. Отмечается только факт отправки с помощью состояния документа.
* ДП. Рассылка производится с учетом способа отправки, возможна рассылка дополнительным адресатам, использование списков рассылки, печать конвертов, формирование заданий на отправку сотрудникам экспедиции.
+
. Контроль.
+
* Может быть указан контролер в задании, возможна приемка исполнения отдельных заданий.
* Предусмотрено два уровня внутреннего контроля: контроль организации и контроль подразделения. Предусмотрена роль "Ответственный исполнитель", если в резолюции учитывается "Внешний контроль" при этом на контроль ставится "Документ".
+
. Отчеты "Исполнителей заданий".
+
* Отчет может быть внесен в предназначенное для этого поле карточки или, если это требуется для завершения задания, добавлен как отдельная карточка.
* Дополнительно реализовано создание документа _Во исполнение_, _Периодические отчеты_.
+
. Автоматизация работы контролера.
+
* Настроена специальная виртуальная папка, в которой отображаются задания в состоянии "На контроле".
* Карточка резолюции содержит специально предназначенные для контроля поля: в ней отображаются все задания резолюции, сроки их исполнения и отчеты по всем подчиненным заданиям.
+
. Изменение разосланных поручений.
+
* Возможны только изменения в отдельных заданиях.
* Возможен отзыв резолюции, изменение сроков от пункта резолюции, добавление пункта резолюции, добавление исполнителя, замена исполнителя, изменение текста резолюции, постановка/снятие с контроля.