= Необходимые ресурсы

[#hardware]
== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению клиентского и серверного компьютера не предъявляются.

NOTE: Результаты замера производительности приведены в xref:admin:Appendix_A.adoc[Приложении A. Производительность].

[#dv]
== Требования к системе {dv}

.. Серверная и части модуля "{dv} 5. {pl}" версии {pl-req} и выше.
.. Серверная и части модуля "{dv} 5. _{bo}_" версии {bo-req} и выше.
.. Серверная и части приложения "{dv} 5. {dm}" версии {dm-req} и выше.
.. Серверная и части модуля "{dv} 5. Управление процессами" версии {wf-req} и выше.
.. Серверная и части модуля "{dv} 5. Конструктор согласований" версии {ad-req} и выше.
.. Серверная и части приложения "{dv} 5. Делопроизводство 4.5" версии {to-req} и выше.
.. Серверная и части модуля "{dv} 5. Windows-клиент" версии {win-req} и выше.

Для работы Приложения необходимо, чтобы в БД {dv} использовались расширенные метаданные. Работа с БД с динамическими метаданными не поддерживается.

[#license]
== Лицензия

Для работы с приложением "Делопроизводство. Версия 5" лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} Office Work 5_.

Максимальное число пользователей, которые могут одновременно работать с функциями приложения, ограничено -- ограничение указано в лицензионной опции.

При отсутствии лицензии будет ограничена возможность работы с карточками и специальными элементами управления приложения.

