= Уровень подготовки пользователя

Для эксплуатации приложения "Делопроизводство. Версия 5" определены две пользовательские роли: администратор {dv} и конечный пользователь. Настройку решения на базе системы {dv} с использованием Приложения выполняет инженер {dv}.

Администратор {dv} устанавливает Приложение (серверную и клиентскую части), выполняет первоначальную настройку.

Инженер {dv} настраивает работу с карточками Приложения с помощью предоставляемых справочников {dv} и Приложения, разрабатывает скрипты карточек.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой и т.п.

Администратор обеспечивает работоспособность процессов Приложения.

Все пользователи Приложения должны обладать базовыми навыками работы на персональном компьютере, в программе "Windows-клиент" (модуль "{dv} 5. Windows-клиент").

Администратор {dv} должен обладать навыками настройки модуля "{dv} 5. {pl}"; а также ознакомиться с документом _Приложение "{dv} 5. Делопроизводство. Версия 5". Руководство администратора_.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}, иметь опыт разработки на языке C#; должен ознакомиться с данным руководством пользователя, документом _Приложение "{dv} 5. Делопроизводство. Версия 5". Руководство администратора_, а также документами _Модуль "{dv} 5. _{bo}_". Руководство администратора_, _Приложение "{dv} 5. {dm}". Руководство администратора_.

Конечные пользователи должны ознакомиться с данным руководством пользователя, а также документами _Модуль "{dv} 5. _{bo}_". Руководство пользователя_, _Приложение "{dv} 5. {dm}". Руководство пользователя_.
