= Аннотация

== Назначение документа

Настоящий документ является руководством администратора приложения "{dv} 5. Делопроизводство. Версия 5" (_Приложение_).

Документ содержит инструкцию по установке и первоначальной настройке Приложения (серверной и клиентской частей).

Документ предназначен для администраторов и инженеров системы {dv}.

== Как организован документ

Настоящее руководство содержит следующие разделы:

[arabic]
. xref:General_information.adoc[Общие сведения] (приведены общие сведения о Приложении, требования Приложения к программному и аппаратному обеспечению компьютера).
. xref:Structureof_program.adoc[Структура Приложения] (перечислены составные части Приложения).
. xref:Install_and_configuration.adoc[Установка и настройка] (содержит инструкцию по установке Приложения).
. xref:Administrator_functions.adoc[Функции администратора] (содержит описание настроек Приложения, выполняемых администратором {dv}).

== Соглашения по оформлению

В данном документе для представления различных терминов и названий используются следующие шрифты и средства форматирования.

* *Жирный* -- используется при написании названий элементов экранного интерфейса и выделения *важной информации*;
* _Курсив_ -- используется для обозначения новых терминов, названий типов и видов карточек;
* http://{dv}.com[Синий] -- используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц;
* `Моноширинный` -- используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним.
