= Приложение A. Производительность

В следующей таблице приведены ориентировочные показатели скорости выполнения основных операций с карточками приложения "Делопроизводство. Версия 5".

[cols=",",options="header"]
|===
|Операция/скорость LAN* |100 Mbps
|Создание резолюции |до 5 сек
|Открытие задания по резолюции (первое/последующие) |до 6 (3) сек
|Открытие документа (первое/последующие) |до 6 (3,5) сек
|Запуск резолюции (10 пунктов) |до 180 сек
|===

*Данные показатели приведены с учетом следующих ограничений:

* аппаратные характеристики клиентского компьютера соответствуют рекомендуемым для модуля "{dv} 5. Windows-клиент" (см. документ Модуль "{dv} 5. Windows-клиент". Руководство администратора, пункт "Необходимое техническое обеспечение");
* на компьютере пользователя не запущены другие программы;
* локальная сеть между клиентским компьютером и сервером {dv} свободна от нагрузки других программ по всей полосе пропускания;
* аппаратные характеристики компьютера с сервером {dv} соответствуют требованиям для текущей нагрузки от работы пользователей и БП;
* в процессе установки модуль "{dv} 5. {pl}" сконфигурирован на "максимальную производительность" (см. Модуль "{dv} 5. {pl}". Руководство администратора, раздел "Первоначальная настройка {dv}").

Указанные значения являются справочными, и справедливы только для конкретных условий измерений и показателей нагрузки, которые использовались в ходе нагрузочного тестирования компанией "ДоксВижн" согласно описанной методике. Несоответствие фактических показателей быстродействия, измеренных в иных условиях, приведенным показателям, не может являться основанием для рекламации или обращения в техническую поддержку.
