= Бизнес-процессы

Приложение добавляет в систему {dv} бизнес-процессы:

[arabic]
. *Делопроизводство 5 - Автозавершение дочерних резолюций*.
+
БП завершения всех дочерних резолюций вниз по дереву резолюций при завершении родительского задания. Запускается при переводе задания в состояние Завершено.
. *Делопроизводство 5 - Автозавершение родительского задания*.
+
БП завершения задания при завершении созданной из него резолюции. Запускается при переводе резолюции в состояние "Завершено".
+
Процесс выполняет следующие действия:
* Получает родительское задание;
* Проверяет, есть ли у задания дочерние резолюции, чье состояние отлично от Завершено;
* Если так резолюций нет, то задание завершается, при этом:
** В поле Отчет добавляются отчеты из подчиненных заданий первого уровня при соблюдении условий:
*** В Справочнике видов карточек в настройках карточки резолюции установлен флаг Добавлять отчет в родительское задание;
*** В таблице исполнителей карточки резолюции в колонке Отчет для данного задания установлена опция Текстовый или Требуется документ во исполнение;
** Копируется ссылка на документ во исполнение из подчиненных заданий первого уровня при соблюдении условий:
*** В таблице исполнителей карточки резолюции в колонке Отчет для данного задания установлена опция Требуется документ во исполнение;
*** Тип ссылки, с которой прикреплен документ, совпадает с указанным для карточки резолюции в Справочнике видов карточек в поле Тип ссылки документа во исполнение.
. *Делопроизводство 5 - Автозавершение родительской резолюции*.
+
БП завершения резолюции при завершении всех ее пунктов. Запускается при переводе карточки группа заданий, соответствующей какому-либо пункту резолюции, в состояние "Завершено". Процесс выполняет следующие действия:
* Получает родительскую резолюцию.
* Проверяет, все ли пункты этой резолюции завершены.
* Если да, завершает резолюцию (переводит в состояние Завершена).
. *Делопроизводство 5 - Запуск резолюции*.
+
БП запуска резолюции на исполнение. Он запускается при переходе резолюции в состояние "Исполняется". Процесс выполняет следующие действия:
* Получает карточку резолюции.
* По каждому из пунктов резолюции формирует карточку группы заданий, в которую вносятся все сведения о пункте (список исполнителей, ответственный, сроки исполнения, текст резолюции и т. д).
* Каждая из карточек группы заданий рассылает задания исполнителям согласно листу исполнения.
. *Делопроизводство 5 - Изменение состояния родительского документа*.
+
БП изменения состояния отправленного на рассмотрение родительского документа при выборе в соответствующем дочернем задании вида На рассмотрение варианта завершения Документ в архив или Документ исполнен. Запускается при переходе задания вида На рассмотрение в состояние "Завершено". Процесс выполняет следующие действия:
* Получает карточку родительского документа. Если таковая отсутствует, бизнес-процесс завершается.
* Переводит карточку родительского документа в одно из состояний:
** Исполнен, если дочернее задание было завершено по кнопке *Документ исполнен*;
** В архиве, если дочернее задание было завершено по кнопке *Документ в архив*.
* После завершения работы экземпляр бизнес-процесса удаляется.
. *Делопроизводство 5 - Отзыв резолюций*.
+
БП отзыва резолюции. Запускается при нажатии в карточке резолюции кнопки *Отозвать* и подтверждении этого действия. Процесс выполняет следующие действия:
* Получает родительскую резолюцию.
* Проверяет, все ли пункты этой резолюции завершены.
* Если нет, отзывает задания незавершенных пунктов (переводит в состояние Отозвано).
. *Делопроизводство 5 - Отзыв дочерних резолюций*.
+
БП отзыва дочерних резолюций при отзыве или завершении родительской резолюции. Запускается при нажатии в карточке родительской резолюции кнопки *Отозвать* и подтверждении этого действия. Процесс выполняет следующие действия:
* Получает родительскую резолюцию.
* Проверяет, все ли пункты этой резолюции завершены.
* Если нет, проверяет, есть ли у незавершенных заданий незавершенные дочерние резолюции.
* Находит незавершенные пункты дочерних резолюций.
* Отзывает незавершенные задания незавершенных пунктов (переводит в состояние Отозвано).
. *Делопроизводство 5 - Отзыв заданий ГЗ*.
+
БП отзыва заданий при отзыве группы заданий. Запускается при нажатии в карточке резолюции кнопки *Отозвать* и подтверждении этого действия.
