= Виды карточек

Приложение "Делопроизводство. Версия 5" добавляет в Справочник видов карточек виды карточек, перечисленные далее.

* Для типа _Документ_ – вид _ДокументДП_ и дочерние виды:
** _Входящий_ – предназначенный для регистрации входящих документов;
** _Информационно-справочный_ – предназначенный для регистрации документов, не выходящих за пределы издавшей его организации и носящих информационно-справочный характер;
** _Исходящий_ – предназначенный для регистрации исходящих (отправляемых из учреждения) документов;
** _Организационный_ – предназначенный для регистрации документов, не выходящих за пределы издавшей его организации и носящих организационный характер;
** _Распорядительный_ – предназначенный для регистрации документов, не выходящих за пределы издавшей его организации и носящих распорядительный характер.
* Для типа _Группа заданий_ – вид _ДП Пункт Резолюции_. Карточка этого вида используется для операций с заданиями пункта резолюции (рассылки заданий по пункту, отзыва всех заданий и т. д). Карточка создается системой автоматически при запуске резолюции на исполнение.
* Для базового типа _Задание_ – дочерние виды:
** _По резолюции_ – используется для совершения операций с отдельным заданием по резолюции в процессе его исполнения; задание этого вида создается системой автоматически при отправке _Резолюции_ на исполнение;
** _На рассмотрение_ – используется для доставки сотруднику документа на рассмотрение и создания по нему резолюции; задание этого вида создается вручную из карточки документа, по которому нужно расписать резолюцию.
