= Папки для работы с карточками Резолюция

Для работы с резолюциями предназначена группа папок "Резолюции", доступная всем пользователям Приложения.

Верхняя папка группы предназначена для создания карточек инициативной Резолюции.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек Резолюция в различных состояниях по различным атрибутам.

Папки для работы с карточками Резолюция:

* *Завершенные в течение года*.
+
В папке отображаются карточки Резолюция в состоянии Завершена, если завершение произошло в течение года.
* *Поиск резолюций*.
+
В папке отображаются карточки Резолюция, удовлетворяющие следующим критериям параметрического поиска:
** состояние;
** номер;
** автор;
** подготовил;
** дата создания (интервал);
** название;
** название пункта;
** исполнители;
** общий срок исполнения (интервал);
** контролёр;
** дата контроля (интервал).
+
Карточки группируются по состоянию.
* *Резолюции на исполнении*.
+
В папке отображаются карточки _Резолюция_ в состоянии На исполнении.
+
Карточки группируются по резолюции.
