= Настройка согласования

Приложение использует маршруты согласования, разработанные с помощью модуля "{dv} 5. Конструктор согласований".

Приложение может работать со встроенными маршрутами согласования приложения "{dv} 5. {dm}" ("Согласование с рецензированием и подписанием" и "Согласование без рецензирования с подписанием"). Для этого требуется доработка маршрутов.

Для настройки запуска согласования:

. Настройте маршруты согласования:
* xref:Completion_of_Built_Agreement.adoc[настройте маршруты согласования] предоставляемые с приложением "{dm}";
* разработайте собственные маршруты согласования.
+
____
Для внесения любых изменений во встроенный маршрут или разработки собственного маршрута согласования требуется лицензия на работу с модулем "Конструктор согласований".
____
. Настройте режимы создания карточки согласования (со способом создания "Создание согласования") из карточек ДокументДП видов: Исходящий, Информационно-справочный, Организационный и Распорядительный. Инструкция приведена в документе _Модуль "{dv} 5. Конструктор согласований". Руководство администратора_, пункт "Настройка создания согласования из карточки документа".
