= Папки для работы с отчетами

Для работы с отчетами предназначена группа папок Отчеты, доступная всем пользователям. Папки данной группы предназначены для отображения сведений о работе пользователя. В стандартной поставке Приложения настроено использование отчетов "Исполнение документов", "Исполнение резолюций" и "Исполнение заданий".

Папки для работы с отчётами:

* *Исполнение документов*.
+
В папке отображаются карточки _ДокументДП_ в состояниях "На рассмотрении", "Зарегистрирован", "На исполнении", удовлетворяющие следующим критериям параметрического поиска:
** период, в который был зарегистрирован документ;
** автор;
** вид документа;
** подразделение.
+
Карточки группируются по состоянию.
* *Исполнение заданий*.
+
В папке отображаются незавершенные задания, удовлетворяющие следующим критериям параметрического поиска:
** исполнитель;
** подразделение исполнителя;
** вид задания;
** срок исполнения.
+
Карточки группируются по исполнителям заданий. Просроченные задания выделяются красным цветом.
* *Исполнение резолюций*.
+
В папке отображаются карточки _Резолюция_ в состоянии "На исполнении", удовлетворяющие следующим критериям параметрического поиска:
** период, в который была создана Резолюция;
** автор;
** подразделение.
