= Настройка личной папки пользователей

Рекомендуется создать в личной папке пользователя папки-делегаты на папки маршрутизации Приложения. При смене состояний карточки автоматически перемещаются по папкам, позволяя пользователю следить за исполнением заданий и резолюций. Также данные папки позволяют быстро найти нужный документ по роли пользователя.

.В Приложении настроены структуры папок маршрутизации, предназначенные для сотрудников, исполняющих определенные роли:
* Папки Делопроизводителя подразделения:
** `Мои документы` -- папка, использующаяся для настройки маршрутизации делопроизводителя подразделения.
* Папки Исполнителя без помощника:
** `Мои задания и резолюции` -- папка, использующаяся для настройки маршрутизации исполнителя, работающего без помощника.
* Папки Исполнителя с помощником:
** `Мои задания и резолюции` -- папка, использующаяся для настройки маршрутизации исполнителя, работающего с помощником.
* Папки Контролёра:
** `Мои задания и документы` -- папка, использующаяся для настройки маршрутизации контролера.
* Папки Помощника исполнителя:
** `Я -- помощник` -- папка, использующаяся для настройки маршрутизации помощника исполнителя.
* Папки Регистратора входящих:
** `Мои документы` -- папка, использующаяся для настройки маршрутизации регистратора входящих документов.

Обратите внимание, что настройки папки `Мои задания и резолюции` для исполнителей, работающих с помощником и без помощника, различаются:

* Для сотрудника, работающего без помощника, в эту папку отбираются все задания, в которых он указан как _Исполнитель_.
* Для сотрудника, работающего с помощником, в эту папку будут отбираться только задания, в которых установлен флаг `*Лично исполнителю*`, а также сотрудник указан как _Исполнитель_.

Перечисленные выше папки располагаются в ветке menu:Папки[{ow} > Служебные > Маршрутизация]. Инструкция по созданию папки-делегата приведена в пользовательской документации модуля {wincl}, раздел xref:winclient:user:folders-create.adoc#delegate[Создание папки типа "Делегат"].

Также пользователям могут быть добавлены папки-делегаты на другие папки ветки menu:Папки[{ow}].
