= Подготовка к работе

После установки Приложения администратор {dv} должен выполнить следующие действия:

. xref:security.adoc#responsible[Назначить] ответственных пользователей Приложения: администраторов номенклатуры дел, контролёров организации и авторов резолюции с возможностью редактирования.
. xref:security.adoc#access[Настроить права доступа] к Справочнику номенклатуры дел 5.
. Создать структуру папок, отвечающую производственным задачам, а также xref:personal-folder.adoc[настроить личные папки] пользователей.
. Добавить (или изменить в соответствии с потребностями организации) в другие справочники все сведения, необходимые для начала работы.
+
Дальнейшие действия не являются обязательными для начала работы с Приложением и могут (при необходимости) быть выполнены позднее.
+
. xref:resolution-template.adoc[Создать шаблоны карточек Резолюция], если планируется создание пользователями карточек резолюции по шаблону.
. Сформировать номенклатуру дел и заполнить Справочник номенклатуры дел 5.
+
Работа со Справочником номенклатуры дел 5 описана в пользовательскоё документации _Приложения {ow}_, раздел xref:user:Ref_Rang_of_cases.adoc[].
