= Необходимое программное обеспечение

== Требования серверной части Модуля

[arabic]
. *Модули {dv}*:
[arabic]
.. Серверная часть модуля "{dv} 5. {pl}" версии 5.5.2 сборка 4553 и выше.
.. Серверная часть модуля "{dv} 5. Базовые объекты" версии 5.5.3 сборка 5367 и выше.
.. Серверная часть приложения "{dv} 5. Управление документами" версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Серверная часть модуля "{dv} 5. Конструктор согласований" версии 5.5.2 сборка 4221 и выше.
.. Серверная часть приложения "{dv} 5. Делопроизводство 4.5" версии 5.5.2 сборка 4203 и выше.
.. Серверная часть модуля "{dv} 5. Windows-клиент" версии 5.5.2 сборка 4248 и выше.

== Требования клиентской части Модуля

[arabic]
. *Модули {dv}*:
[arabic]
.. Клиентская часть модуля "{dv} 5. {pl}" версии 5.5.2 сборка 4553 и выше.
.. Серверная часть модуля "{dv} 5. Базовые объекты" версии 5.5.3 сборка 5367 и выше.
.. Клиентская часть приложения "{dv} 5. Управление документами" версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Клиентская часть модуля "{dv} 5. Конструктор согласований" версии 5.5.2 сборка 4221 и выше.
.. Клиентская часть приложения "{dv} 5. Делопроизводство 4.5" версии 5.5.2 сборка 4203 и выше.
.. Клиентская часть модуля "{dv} 5. Windows-клиент" версии 5.5.2 сборка 4248 и выше.
. *Дополнительное программное обеспечение*:
[arabic]
.. Microsoft Internet Explorer footnote:[Необходимо для корректного отображения карточки Резолюция в форме для чтения.] версии 9, 10 или 11.
