= Настройка ролевой модели

Ролевая модель безопасности для работы с карточками Приложения настраивается в _Конструкторе ролей_, см. документацию модуля _{bo}_, раздел "xref:6.1@backoffice:desdirs:roles/designer.adoc[]".

Описание стандартных ролей Приложения приведено в разделе xref:ROOT:roles.adoc[Роли].

Для настройки ролевой модели администратор должен использовать хранимые процедуры, иначе в карточках резолюций и заданий сотрудник увидит дерево резолюций, часть узлов в котором (соответствующих карточкам, на которые он не имеет прав на чтение) будут пусты.

С Приложением предоставляются следующие хранимые процедуры, файлы размещаются в папке `C:\Program Files (x86)\{dv}\OfficeWork\5.5\Server\Database\Sql`:

* `dvow_Operand_GetResolutionPerformers`
+
Процедура возвращает список из исполнителей, авторов и контролеров всех резолюций из дерева резолюций. Применение процедуры в ролевой модели позволяет стандартным образом выдать пользователю права на все карточки резолюций в дереве резолюций, если хотя бы в одной из них он указан как автор, исполнитель или контролер.
+
С помощью этой хранимой процедуры настроена роль _Читатель_ дерева резолюций для карточек резолюций. Роли даны права на чтение карточек.
+
Хранимая процедура должна использоваться при настройке роли карточки резолюции.
+
* `dvow_Operand_GetTaskReaders`
+
Процедура возвращает список из исполнителей, авторов и контролеров всех заданий из дерева резолюций. Применение процедуры в ролевой модели позволяет выдать пользователю права на все карточки заданий в дереве резолюций, если хотя бы в одной из них он указан как автор, исполнитель или контролер.
+
С помощью этой хранимой процедуры настроена роль Читатель дерева резолюций для карточек заданий. Роли даны права на чтение карточек.
+
Хранимая процедура должна использоваться при настройке роли карточки задания.
* `dvow_Operand_Document_AgreementPartner`
+
Процедура возвращает список из участников согласования документа согласно настройкам маршрута согласования. Применение процедуры в ролевой модели позволяет выдать пользователю права карточку документа, если он принимает участие в его согласовании.
+
С помощью этой хранимой процедуры настроена роль Участник согласования для карточек ДокументДП. Роли даны права на чтение карточки исходного документа.
+
* `dvow_Operand_Document_LinkedTaskPartner`
+
Процедура возвращает список из участников заданий и резолюций, созданных по документу по всему дереву резолюций, а также участников резолюции, к заданию которой текущий документ приложен в качестве отчета. Применение процедуры в ролевой модели позволяет выдать пользователю права карточку документа, если он принимает участие в связанном с документом задания.
+
С помощью этой хранимой процедуры настроена роль _Участник_ связанного задания для карточек _ДокументДП_. Роли даны права на чтение карточки документа.
+
* `dvow_Operand_Document_LinkedDocumentPartner`
+
Процедура возвращает список из участников всех документов, на которые имеется ссылка в текущем документе. Применение процедуры в ролевой модели позволяет выдать пользователю права карточку документа, если он принимает участие в связанном документе.
+
С помощью этой хранимой процедуры настроена роль _Участник_ связанного документа для карточек _ДокументДП_. Роли даны права на чтение карточки документа.
+
* `dvow_Operand_Document_ResponsDepartmentPartner`
+
Процедура возвращает список из всех сотрудников данного подразделения и всех подразделений ниже по иерархии. Применение процедуры в ролевой модели позволяет выдать пользователю права карточку документа, если он является сотрудником подразделения.
+
С помощью этой хранимой процедуры настроена роль _Сотрудник_ подразделения документа для карточек _ДокументДП_. Роли даны права на чтение карточки документа.
