= Роли

В Приложении используется набор типовых ролей, определяющих права доступа к документам и возможность выполнения операций с карточками:

* Для работы с карточкой _Резолюция_:
** _Контролер_ – сотрудник, указанный в поле Контролёр;
** _Автор_ – сотрудник, указанный в поле Автор – по умолчанию текущий сотрудник;
** _Подготовил_ – сотрудник, создавший документ в системе – по умолчанию текущий сотрудник;
** _Читатель дерева резолюций_ – сотрудник, которому даны права на чтение карточек резолюций в дереве резолюций;
** _Автор-редактор_ – сотрудник, для которого карточка _Резолюция_ в состоянии На утверждение будет открыта в редактируемой форме;
** _Администратор УД_ – сотрудник, которому в карточке _Резолюция_ доступна разметка "Настройка" и, как следствие, кнопка ленты Дизайн.
* Для работы с карточкой _Дело_:
** _Администратор ДП5_ – сотрудник из группы "Администратор номенклатуры дел" Справочника сотрудников, имеющий право на работу с карточкой _Дело_;
** _Все остальные пользователи_ – пользователи, имеющие право на чтение карточки _Дело_.
* Для работы с карточкой _Задание - По резолюции_:
** _Контролер_ – сотрудник, указанный в поле Контролёр;
** _Заместитель исполнителя_ – заместитель исполнителя задания по резолюции;
** _Исполнитель_ – исполнитель задания по резолюции;
** _Все руководители_ – руководитель и его заместители для регистратора и участников исполнения резолюции;
** _Автор_ – сотрудник, указанный в поле Автор – по умолчанию текущий сотрудник;
** _Делегировавший_ – сотрудник, делегировавший полученное задание по резолюции;
** _Заместитель автора_ – заместитель сотрудника, указанного в поле Автор;
** _Читатель дерева резолюций_ – сотрудник, которому даны права на чтение карточек заданий в дереве резолюций;
** _Ответственный исполнитель_ – ответственный исполнитель пункта (группы заданий) резолюции.
* Для работы с карточкой _Задание - На рассмотрение_:
** _Все руководители_ – руководитель и его заместители для регистратора и участников исполнения резолюции;
** _Делегировавший_ – сотрудник, делегировавший полученное задание по резолюции;
** _Исполнитель_ – исполнитель задания по резолюции;
** _Заместитель исполнителя_ – заместитель исполнителя задания по резолюции;
** _Заместитель автора_ – заместитель сотрудника, указанного в поле Автор;
** _Автор_ – сотрудник, указанный в поле Автор – по умолчанию текущий сотрудник;
** _Читатель дерева резолюций_ – сотрудник, которому даны права на чтение карточек заданий в дереве резолюций.
* Для работы с карточкой _ДокументДП - Входящий_:
** _Делопроизводитель_ – сотрудник, создавший документ в системе и зарегистрировавший его; после регистрации может отправить документ в архив; может выполнять шифрование файлов;
** _Получатель_ – адресат документа;
** _Все руководители_ – руководитель и его заместители для всех сотрудников, исполняющих в карточке документа какую-либо роль;
** _Контролер_ – сотрудник, которое будет осуществлять общий контроль карточки;
** _Участник согласования_ – сотрудник, участвующий в согласовании документа согласно настройкам маршрута согласования;
** _Участник связанного задания_ – сотрудник, исполняющий роль в задании, содержащем ссылку на текущий документ;
** _Участник связанного документа_ – сотрудник, исполняющий роль в документе, на который имеется ссылка в текущем документе;
** _Сотрудник подразделения документа_ – сотрудник подразделения, указанного в поле Подразделение документа или подразделений, стоящих ниже по иерархии.
* Для работы с карточкой _ДокументДП - Информационно-справочный_:
** _Подготовил_ – сотрудник, создавший документ в системе – по умолчанию текущий сотрудник; может выполнять шифрование файлов;
** _Получатель_ – адресат документа;
** _Все руководители_ – руководитель и его заместители для всех сотрудников, исполняющих в карточке документа какую-либо роль;
** _Контролер_ – сотрудник, которое будет осуществлять общий контроль карточки;
** _Автор_ – сотрудник, указанный в поле Автор – по умолчанию текущий сотрудник;
** _Делопроизводитель_ – сотрудник, регистрирующий документы; после регистрации может отправить документ на рассмотрение или на исполнение, списать в архив; может выполнять шифрование файлов;
** _Участник согласования_ – сотрудник, участвующий в согласовании документа согласно настройкам маршрута согласования;
** _Участник связанного задания_ – сотрудник, исполняющий роль в задании, содержащем ссылку на текущий документ;
** _Участник связанного документа_ – сотрудник, исполняющий роль в документе, на который имеется ссылка в текущем документе;
** _Сотрудник подразделения документа_ – сотрудник подразделения, указанного в поле Подразделение документа или подразделений ниже по иерархии.
* Для работы с карточкой _ДокументДП - Исходящий_:
** _Автор_ – сотрудник, указанный в поле Автор – по умолчанию текущий сотрудник;
** _Подготовил_ – сотрудник, создавший документ в системе – по умолчанию текущий сотрудник; может выполнять шифрование файлов;
** _Все руководители_ – руководитель и его заместители для всех сотрудников, исполняющих в карточке документа какую-либо роль;
** _Делопроизводитель_ – сотрудник, регистрирующий документы; после регистрации может отправить документ получателям (если получатели не были определены ранее, то перед отправкой указывает их); может выполнять шифрование файлов;
** _Сотрудник подразделения документа_ – сотрудник подразделения, указанного в поле Подразделение документа или подразделений ниже по иерархии;
** _Участник связанного документа_ – сотрудник, исполняющий роль в документе, на который имеется ссылка в текущем документе;
** _Участник связанного задания_ – сотрудник, исполняющий роль в задании, содержащем ссылку на текущий документ;
** _Участник согласования_ – сотрудник, участвующий в согласовании документа согласно настройкам маршрута согласования.
* Для работы с карточкой _ДокументДП - Организационный_:
** _Автор_ – сотрудник, указанный в поле Автор – по умолчанию текущий сотрудник;
** _Подготовил_ – сотрудник, создавший документ в системе – по умолчанию текущий сотрудник; может выполнять шифрование файлов;
** _Все руководители_ – руководитель и его заместители для всех сотрудников, исполняющих в карточке документа какую-либо роль;
** Делопроизводитель – сотрудник, регистрирующий документы; после регистрации может отправить документ на ознакомление, списать в архив; может выполнять шифрование файлов;
** _Сотрудник подразделения документа_ – сотрудник подразделения, указанного в поле Подразделение документа или подразделений ниже по иерархии;
** _Участник связанного документа_ – сотрудник, исполняющий роль в документе, на который имеется ссылка в текущем документе;
** _Участник связанного задания_ – сотрудник, исполняющий роль в задании, содержащем ссылку на текущий документ;
** _Участник согласования_ – сотрудник, участвующий в согласовании документа согласно настройкам маршрута согласования.
* Для работы с карточкой _ДокументДП - Распорядительный_:
** _Подготовил_ – сотрудник, создавший документ в системе – по умолчанию текущий сотрудник; может выполнять шифрование файлов;
** _Получатель_ – адресаты документа;
** _Все руководители_ – руководитель и его заместители для всех сотрудников, исполняющих в карточке документа какую-либо роль;
** _Контролер_ – сотрудник, которое будет осуществлять общий контроль карточки;
** _Автор_ – сотрудник, указанный в поле Автор, по умолчанию текущий сотрудник;
** _Делопроизводитель_ – сотрудник, регистрирующий документы; после регистрации может отправить документ на рассмотрение, на исполнение или списать в архив; может выполнять шифрование файлов;
** _Сотрудник подразделения документа_ – сотрудник подразделения, указанного в поле Подразделение документа или подразделений ниже по иерархии;
** _Участник связанного документа_ – сотрудник, исполняющий роль в документе, на который имеется ссылка в текущем документе;
** _Участник связанного задания_ – сотрудник, исполняющий роль в задании, содержащем ссылку на текущий документ;
** _Участник согласования_ – сотрудник, участвующий в согласовании документа согласно настройкам маршрута согласования.
* Общая роль:
** _Системная для WF_ – сотрудник из группы "Системная для WF" Справочника сотрудников, имеющий максимально возможные права при работе с карточками Приложения.
