= Настройки безопасности

[#responsible]
== Назначение ответственных пользователей Приложения

При установке приложения "{ow}" в Справочник сотрудников добавляется несколько групп, предназначенных для назначения ответственных пользователей, а именно группы: _Автор резолюции -- редактор_, _Администратор номенклатуры дел_ и _Контролеры организации_. Назначение указанных групп приведено в пункте xref:ROOT:groups.adoc[Служебные группы].

.Для назначения ответственного пользователя Приложения:
. Запустите {wincl} от имени администратора {dv}.
. Откройте Справочник сотрудников.
. Выдайте себе права на редактирование групп _Автор резолюции -- редактор_, _Администратор номенклатуры дел_ и _Контролеры организации_ по дискреционной модели безопасности, см. документацию модуля {wincl}, раздел "xref:dev@winclient:user:security.adoc[]".
. Включите ответственного сотрудника в одну или несколько из указанных групп Приложения.

[#access]
== Настройка прав доступа к Справочнику номенклатуры дел 5

По умолчанию редактировать Справочник номенклатуры дел 5 имеют право все пользователи {dv}.

Чтобы ограничить доступ к справочнику, настройте права доступа к нему по дискреционной модели безопасности, см. документацию модуля {wincl}, раздел "xref:dev@winclient:user:security.adoc[]".

. Назначьте учетной записи определенного пользователя полные права на чтение и редактирование справочника.
. Отберите у учетной записи _Все_ все права на справочник за исключением права на чтение.
+
Пользователи, не имеющие прав чтения _Справочника номенклатуры дел 5_, не смогут привязать документ к карточке _Дело_.
