= Настройки карточки задания "По резолюции"

Вид карточки задания По резолюции разработан для работы с заданиями в приложении "Делопроизводство. Версия 5". При необходимости администратор может разработать и использовать для работы с резолюцией свой вид карточки Задание.

Настройка вида карточки задания По резолюции осуществляется в Справочнике видов карточек. Описание настроек карточки вида Задание приведено в документе (см. документ _Модуль "{dv} 5. _{bo}_". Руководство администратора_, пункт "Настройки типа `Задание'"). При настройке обратите внимание на следующее:

* В настройках типов ссылок для основного документа можно установить флаг *Копировать в дочернее* в окне "Редактирование". В этом случае в карточки дочерних резолюций будет скопирована ссылка на исполняемый документ родительского задания.
* На странице "Подчиненное задание" можно указать список полей родительского задания, значения которых должны копироваться в подчиненную резолюцию при ее создании. По умолчанию копируются значения полей "Название", "Содержание", "Дата завершения плановая".
