= Настройка автомата состояний

Автомат состояний карточек Приложения настраивается в _Конструкторе состояний_? см. документацию модуля _{bo}_, раздел "xref:6.1@backoffice:desdirs:states/designer.adoc[]".

Приложение содержит преднастроенные автоматы состояний для карточки _ДокументДП_ всех видов, карточки _Резолюция_, карточки _Дело_, заданий _По резолюции_, _На рассмотрение_ и _На ознакомление_.

Редактировать разрешено только автоматы состояний, настроенные администратором для самостоятельно разработанных видов карточек.

[#card-state]
== Включение состояния карточки документа в жизненный цикл карточки

После установки Приложения _Конструктор состояний_ будет содержать не включенные в автомат состояний состояния для карточек _ДокументДП_ вида _Входящий_, _Информационно-справочный_, _Исходящий_, _Организационный_ и _Распорядительный_.

Чтобы включить поставляемое состояние в автомат состояний, выполните следующие действия:

. Откройте _Конструктор состояний_ и выберите вид карточки _ДокументДП_, для которого нужно изменить автомат состояний.
. Переместите пиктограмму добавляемого в автомат состояния так, чтобы удобно было настраивать переходы между состояниями. Определите переходы между состояниями, которые свяжут добавленное состояние с другими состояниями автомата.
+
В раскрывающийся список кнопки *Выполнить* карточки документа настраиваемого вида будет добавлена операция перевода в добавленное состояние.
. Откройте _Конструктор ролей_ и выберите вид карточки _ДокументДП_, для которого был изменен автомат состояний.
. Перейдите на вкладку _Матрица доступа_ и определите права на добавленную операцию.
