= Структура Приложения

Приложение "Делопроизводство. Версия 5" состоит из двух частей:

[arabic]
. Серверная часть (для установки на компьютер с сервером {dv}) включает следующие элементы:
[arabic]
.. Схемы метаданных типов карточек:
* карточка Резолюция предназначена для формирования, рассылки и учета выданных заданий и контроля их исполнения. Каждая резолюция может состоять из нескольких пунктов, по каждому пункту может быть указано несколько исполнителей;
* карточка Дело предназначена для хранения сведений о деле Справочника номенклатуры дел 5;
* Справочник номенклатуры дел 5 предназначен для регистрации места хранения бумажных документов, а также для классификации документов организации;
.. Загружаемые в систему {dv} данные: xref:CardSubtypes_DocManagement.adoc[виды карточек], xref:Role_model.adoc[роли], xref:Folder_Application_OfficeWork.adoc[папки], xref:Groups.adoc[группы сотрудников], xref:BP_DocManagement_templates.adoc[бизнес-процессы], скрипты карточек.
.. Пакет установки клиентской части приложения "Делопроизводство. Версия 5".
. Клиентская часть (для установки на компьютеры пользователей {dv}) включает следующие элементы:
[arabic]
.. Библиотеки DLL с компонентом библиотеки карточек, элементами пользовательского интерфейса карточек Приложения (для Windows-клиента и РМА).
