= Настройки карточки задания "По резолюции"

Вид карточки задания По резолюции разработан для работы с заданиями в приложении "{ow}". При необходимости администратор может разработать и использовать для работы с резолюцией свой вид карточки Задание.

Настройка вида карточки задания По резолюции осуществляется в _Справочнике видов карточек_. Описание настроек карточки вида _Задание_ приведено в документе, см. подробнее документацию модуля _{bo}_, см. раздел "xref:dev@backoffice:desdirs:card-kinds/task/settings-parameters.adoc[]".

.При настройке обратите внимание на следующее:
* В настройках типов ссылок для основного документа можно установите флаг `*Копировать в дочернее*` в окне _Редактирование_. В этом случае в карточки дочерних резолюций будет скопирована ссылка на исполняемый документ родительского задания.
* На странице _Подчиненное задание_ можно указать список полей родительского задания, значения которых должны копироваться в подчиненную резолюцию при её создании. По умолчанию копируются значения полей _Название_, _Содержание_, _Дата завершения плановая_.
