= Перечень терминов и их определений

* *Администратор {dv}*.
+
Пользователь системы {dv}, который подготавливает функциональную среду для установки {dv}; устанавливает модули и приложения {dv}; выполняет первоначальную настройку {dv}; управляет доступом других пользователей в систему {dv}.
+
Должен быть членом группы пользователей "{dv} Administrators" на компьютере с сервером {dv}.
* *Администратор КС*.
+
Сотрудник, настраивающий процесс согласования документов с помощью модуля "{dv} 5. Конструктор согласований".
+
Должен быть членом группы сотрудников "Администраторы КС" в Справочнике сотрудников.
* *Атрибутивный поиск*.
+
Вариант поискового запроса, который выполняется по полям (атрибутам) карточки.
* *Базовый модуль*.
+
Модуль {dv}, который является частью стандартного комплекта поставки системы {dv}. Примером базового модуля является модуль "{dv} 5. {pl}".
* *Внешнее хранилище*.
+
Хранилище бинарных данных файлов.
* *Делегировавший*.
+
Сотрудник, который делегировал задание другому исполнителю.
* *Дополнительный модуль*.
+
Модуль {dv}, который не входит в стандартный комплект поставки системы {dv}. Примером дополнительного модуля является модуль "{dv} 5. Web-клиент".
* *Инженер {dv}*.
+
Пользователь системы {dv}, настраивающий {dv} для конечного пользователя с помощью предоставляемых конструкторов и справочников {dv}, а также других программных средств.
+
Пользователь, являющийся инженером {dv}, должен быть членом группы безопасности "{dv} Administrators" на компьютере с сервером {dv}.
* *Инициатор согласования*.
+
Сотрудник, который инициировал процесс согласования или управляет запущенным согласованием.
* *Исполнитель*.
+
Текущий исполнитель задания, а также его постоянные/временные заместители.
* *Карточка*.
+
Объект системы {dv}, предназначенный для упорядоченного хранения сведений о внешних объектах и процессах, информация о которых является предметом учета, хранения и обработки.
* *Конструктор*.
+
Карточка, являющаяся инструментом настройки определенной функциональности системы {dv}. В {dv} каждый конструктор существует в единственном экземпляре.
* *Конечный пользователь {dv}*.
+
Пользователь системы {dv}, осуществляющий в рамках своих должностных обязанностей операции электронного документооборота (регистрация, согласование документов и т. п.) с помощью {dv}.
+
Если отсутствует уточнение, то под пользователем системы {dv} подразумевается конечный пользователь {dv}.
+
Пользователь {dv}, должен быть членом группы безопасности "{dv} Users" на компьютере с сервером {dv}.
* *Конкурентная лицензия*.
+
Лицензия, выдаваемая любому пользователю при подключении к серверу {dv}. Лицензия выдается из ограниченного пула лицензий, что лимитирует число одновременно работающих с системой {dv} пользователей.
* *Модуль {dv}*, *Приложение {dv}*.
+
Устанавливаемый компонент системы {dv}, который добавляет новую функциональность системы {dv} или предоставляет дополнительные средства для работы с системой {dv}.
* *Неконкурентная лицензия*.
+
Лицензия, назначаемая определенному пользователю, которая обеспечивает ему гарантированный доступ в систему {dv}, когда все конкурентные лицензии используются.
* *Ответственный исполнитель*.
+
Сотрудник, отвечающий за исполнение заданий группы заданий, который может завершать задания других исполнителей, осуществлять контроль и приемку.
* *Папка*.
+
Карточка, содержащая ярлыки на другие карточки.
* *Поисковый запрос*.
+
Настраиваемый запрос к базе данных {dv}, который возвращает карточки, соответствующие установленным в запросе критериям.
* *Полнотекстовый поиск*.
+
Вариант поискового запроса, который выполняется по содержимому карточки.
* *Представление*.
+
Табличная форма отображения данных карточек, содержащихся в папке или возвращаемых поисковым запросом.
* *Разметка карточки*.
+
Графическое представление данных карточки. Разметка содержит схему расположения элементов управления в предоставляемой пользователю форме, связи элементов управления с данными карточки, настройки элементов управления и формы.
* *Регистратор*.
+
Сотрудник, создавший документ в системе {dv}.
* *Решение {dv}*.
+
Разработанное на базе системы {dv} прикладное решение, которое предназначено для организации и выполнения электронного документооборота в определенной отрасли.
* *Сателлитная база данных*.
+
Дополнительная база данных {dv}, в которую вытеснены данные из основной базы данных {dv}.
* *Сервер {dv}*.
+
Компонент модуля "{dv} 5. {pl}", который отвечает за низкоуровневую работу с имеющимися в БД данными и поддерживает их целостность, проверяет права доступа и обеспечивает получение и отправку клиентскими компонентами пакетов данных, обеспечивает поиск элементов, реализует функции точки подключения клиентских программ (Windows-клиента, Web-клиента и др.). Под сервером {dv} подразумевается веб-служба IIS и служба ОС Windows, которые обеспечивают указанные функции.
* *Сервис полнотекстового индексирования*.
+
Служба {dv}, которая обеспечивает передачу предусмотренных данных {dv} интегрированному полнотекстовому поиску Microsoft SQL Server или внешней поисковой системе (например, системе полнотекстового поиска Elasticsearch) для обеспечения работы функции полнотекстового поиска в {dv}. Является частью модуля "{dv} 5. {pl}".
* *Сервис управления бизнес-процессами*, *СУБП*.
+
Служба {dv}, которая обеспечивает обработку бизнес-процессов. Является частью модуля "{dv} 5. Управление процессами".
* *Справочник*.
+
Карточка, предназначенная для хранения информации о различных объектах. В системе {dv} каждый справочник существует в единственном экземпляре.
* *Участник согласования*.
+
Сотрудник, участвующий в исполнении заданий, разосланных в ходе выполнения согласования документа.
* *Шаблон карточки*.
+
Карточка с предопределенным набором данных, из которой могут быть созданы экземпляры карточки с аналогичным набором данных.
