= Приемка подразделения

Если при формировании пункта резолюции в поле Вид приемки установлено значение "Приемка подразделения", задание ответственного исполнителя после завершения передается на приемку (то есть переходит в состояние "На приемке").

____
Если в пункте резолюции не выбран ответственный исполнитель, на приемку будут переданы все задания этого пункта.
____

Приемку подразделения проводит сотрудник, указанный в поле Контролер или, если он не назначен, автор резолюции.

Для проведения приемки выполните следующие действия:

. Перейдите в папку `На приемке` и найдите в группе заданий в состоянии "На приемке" интересующее задание.
. Откройте полученное задание.
. Ознакомьтесь с результатами выполнения задания.
. Выполните доступные операции с заданием:
* Подтвердите приемку. Для этого нажмите на кнопку *Выполнить* → *Принять*. Задание перейдет в состояние "Завершено".
* Отправьте задание на доработку. Для этого нажмите на кнопку *Выполнить* → *На доработку*. Задание перейдет в состояние "На доработке".
* При необходимости выполните другие доступные операции с заданием.
