= Приемка организации

Если при формировании пункта резолюции в поле Вид приемки установлено значение "Приемка организации", задание ответственного исполнителя (если он указан) или все задания данного пункта (если ответственный не выбран), после его завершения, переходит в состояние "На приемке".

Задания на приемку приходят одновременно всем сотрудникам, включенным в группу "Контролёры организации" в Справочнике сотрудников. Контролёром, проводящим приемку, будет назначен сотрудник, первым взявший задание в работу.

Для проведения приемки выполните следующие действия:

[arabic]
. Перейдите в папку `На приемке` и найдите в группе заданий в состоянии "На приемке" интересующее задание.
. Откройте полученное задание и нажмите кнопку *Начать приёмку*.
+
Текущий пользователь будет внесен в поле Контролер карточки задания.
. Ознакомьтесь с результатами выполнения задания.
. Выполните доступные операции с заданием:
* Подтвердите приемку. Для этого нажмите на кнопку *Выполнить* → *Принять*. Задание перейдет в состояние "Завершено".
* Отправьте задание на доработку. Для этого нажмите на кнопку *Выполнить* → *На доработку*. Задание перейдет в состояние "На доработке".
* При необходимости выполните другие доступные операции с заданием.
