= Прикрепление файлов и документов к карточке резолюции

К карточке Резолюция может быть прикреплено произвольное количество файлов различных форматов и карточек документов.

____
*Для инициативных резолюций, создаваемых непосредственно из {wincl}а, добавление исполняемых документов в карточку не поддерживается*. В такие резолюции могут быть добавлены только ссылки на вспомогательные документы.
____

Прикрепить документ к резолюции можно, если карточка Резолюция находится в состоянии "Подготавливается", "На утверждении" и "На доработке".

Чтобы прикрепить файлы и/или документы к карточке резолюции:

. Откройте карточку Резолюция и перейдите на вкладку Комментарии и дополнения.
. Для прикрепления к резолюции уже существующей карточки выполните следующие действия:
.. Выберите из контекстного меню таблицы Документы пункт Добавить карточку.
.. В открывшемся окне Выберите карточки отметьте требуемую карточку и нажмите кнопку выбора .
+
Ссылка на карточку документа будет помещена в таблицу "Документы:".
. Для прикрепления к резолюции файла из файловой системы выполните следующие действия:
.. Выберите из контекстного меню таблицы Файлы пункт Добавить файл → Документ → Файл.
.. Выберите требуемый файл.
+
Ссылка на карточку файла будет помещена в таблицу Файлы.
