= Создание заданий На исполнение и групп заданий по документу

Задания позволяют создавать распоряжения по документу, предназначенные определенным исполнителям. Например, при помощи заданий можно отправить документ на ознакомление другим сотрудникам с приложенным сопроводительным документом или исполнить данное руководителем поручение.

Каждое задание снабжено описанием работ, сроками их исполнения и другими параметрами, а также предусматривает необходимый контроль за ходом его реализации.

Задание предназначено для выполнения одним исполнителем. Если в задании указано несколько исполнителей, работа будет выполняться тем из них, кто первым возьмет задание в работу. Для создания заданий, не связанных с наложением резолюции на документ, используются карточки Задание УД видов:

* На ознакомление (см. xref:Sending_to_Familiarize.adoc[Рассылка документа на ознакомление]);
* На исполнение.

Для заданий, предполагающих исполнение несколькими сотрудниками, предназначены группы заданий.

Описание создания и работы с заданиями на исполнение и группами заданий приведено в документе _Приложение "{dv} 5. {dm}". Руководство пользователя_.
