= Работа с исходящим документом

Настройки приложения "Делопроизводство. Версия 5" предполагают следующий порядок обработки исходящих документов:

* Подготовка проекта документа. Согласование и подписание документа.
. Сотрудник, исполняющий роль "Подготовил" выполняет следующие действия:
** создает карточку документа в общей папке Исходящие;
** указывает атрибуты карточки;
** прикрепляет файл документа;
** рассылает документ на согласование или вручную фиксирует факт его подписания.
+
____
На этапе подготовки после первого сохранения документу автоматически присваивается временный номер.
____
* Регистрация.
+
Регистрацию подготовленного документа выполняет делопроизводитель:
** делопроизводитель получает документы в состоянии "Подписан" на регистрацию в виртуальную папку На регистрацию, расположенную в его личной папке;
** знакомится с документом, при необходимости добавляет дополнительный файл или комментарий;
** делопроизводитель получает документ с временным регистрационным номером и может присвоить постоянный регистрационный номер либо руками, либо автоматически после выполнения регистрации;
** регистрирует документ, нажав кнопку на панели инструментов Зарегистрировать, при этом:
*** документ переходит в состояние "Зарегистрирован";
*** выделяется постоянный номер (если ещё не выделен);
*** если поле Дата регистрации пусто, его значением устанавливается текущая дата.
+
Зарегистрированные документы отображаются в одноименной виртуальной папке, расположенной в личной папке делопроизводителя.
* Работа с документом после регистрации.
+
Зарегистрированный исходящий документ делопроизводитель может:
** отправить на ознакомление;
** отправить получателям; если в документе не указаны получатели, перед отправкой потребуется их указать.
