= Папки для работы с организационными документами

Папка `Организационные` предназначена для создания карточек ДокументДП -- Организационный и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек ДокументДП -- Организационный в различных состояниях по различным атрибутам.

. Архив организационных.
+
Организационные документы и все их дочерние документы в состоянии "В архиве".
. Журнал организационных.
+
Организационные документы и все их дочерние документы, зарегистрированные в текущем году.
. Поиск организационных.
+
Список карточек ДокументДП -- Организационный, удовлетворяющих следующим критериям параметрического поиска:
* состояние;
* статус;
* числовая часть временного регистрационного номера (интервал);
* числовая часть постоянного регистрационного номера (интервал);
* название;
* автор;
* дата регистрации (интервал);
* подготовил (можно задать несколько);
* подразделение;
* признак контроля.
. Проекты организационных Незарегистрированные организационные документы и все их дочерние документ.
