= Папки для работы с исходящими документами

Папка `Исходящие` предназначена для создания карточек _ДокументДП -- Исходящий_ и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек _ДокументДП -- Исходящий_ в различных состояниях по различным атрибутам.

. Архив исходящих.
+
Входящие документы и все их дочерние документы в состоянии _В архиве_.
+
. Журнал исходящих.
+
Входящие документы и все их дочерние документы, зарегистрированные в текущем году.
+
. Поиск исходящих.
+
Список карточек _ДокументДП -- Исходящий_, удовлетворяющих следующим критериям параметрического поиска:
+
* Состояние.
* Числовая часть временного регистрационного номера -- интервал.
* Числовая часть постоянного регистрационного номера -- интервал.
* Название.
* Автор.
* Дата регистрации -- интервал.
* Подготовил.
* Получатели -- контрагенты.
* Подразделение, признак контроля.
+
. Проекты исходящих.
+
Незарегистрированные исходящие документы и все их дочерние документы.
