= Папки для работы с организационными документами

Папка `Организационные` предназначена для создания карточек _ДокументДП -- Организационный_ и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек _ДокументДП -- Организационный_ в различных состояниях по различным атрибутам.

. Архив организационных.
+
Организационные документы и все их дочерние документы в состоянии `В архиве`.
+
. Журнал организационных.
+
Организационные документы и все их дочерние документы, зарегистрированные в текущем году.
+
. Поиск организационных.
+
Список карточек _ДокументДП -- Организационный_, удовлетворяющих следующим критериям параметрического поиска:
+
* Состояние.
* Статус.
* Числовая часть временного регистрационного номера (интервал).
* Числовая часть постоянного регистрационного номера (интервал).
* Название.
* Автор.
* Дата регистрации (интервал).
* Подготовил (можно задать несколько).
* Подразделение.
* Признак контроля.
+
. Проекты организационных Незарегистрированные организационные документы и все их дочерние документы.
