= Папки для работы с исходящими документами

Папка `Исходящие` предназначена для создания карточек ДокументДП - Исходящий и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек ДокументДП - Исходящий в различных состояниях по различным атрибутам.

[arabic]
. Архив исходящих.
+
Входящие документы и все их дочерние документы в состоянии "В архиве".
. Журнал исходящих.
+
Входящие документы и все их дочерние документы, зарегистрированные в текущем году.
. Поиск исходящих.
+
Список карточек ДокументДП - Исходящий, удовлетворяющих следующим критериям параметрического поиска:
* состояние;
* числовая часть временного регистрационного номера (интервал);
* числовая часть постоянного регистрационного номера (интервал);
* название;
* автор;
* дата регистрации (интервал);
* подготовил;
* получатели (контрагенты);
* подразделение;признак контроля.
. Проекты исходящих.
+
Незарегистрированные исходящие документы и все их дочерние документы.
