= Папки для работы с входящими документами

Папка `Входящие` предназначена для создания карточек ДокументДП -- Входящий и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек ДокументДП -- Входящий в различных состояниях по различным атрибутам.

. Архив входящих.
+
Входящие документы и все их дочерние документы в состоянии "В архиве"
. Входящие на исполнении.
+
Входящие документы и все их дочерние документы в состоянии "На исполнении".
. Входящие на рассмотрении.
+
Входящие документы и все их дочерние документы в состоянии "На рассмотрении".
. Журнал входящих Входящие документы и все их дочерние документы, зарегистрированные в текущем году
. Поиск входящих.
+
Список карточек ДокументДП -- Входящий, удовлетворяющих следующим критериям параметрического поиска:
* состояние;
* числовая часть постоянного регистрационного номера (интервал);
* название;
* организация-отправитель;
* дата регистрации (интервал);
* регистратор входящих;
* получатели (сотрудники);
* подразделение;
* признак контроля
