= Папки для работы с информационно-справочными документами

Папка `Информационно-справочные` предназначена для создания карточек _ДокументДП -- Информационно-справочный_ и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек _ДокументДП -- Информационно-справочный_ в различных состояниях по различным атрибутам.

. Архив информационно-справочных.
+
Информационно-справочные документы и все их дочерние документы в состоянии _В архиве_.
+
. Журнал информационно-справочных.
. Информационно-справочные документы и все их дочерние документы, зарегистрированные в текущем году.
. Информационно-справочные на исполнении.
+
Информационно-справочные документы и все их дочерние документы в состоянии _На исполнении_.
+
. Информационно-справочные на рассмотрении.
+
Информационно-справочные документы и все их дочерние документы в состоянии _На рассмотрении_.
+
. Поиск информационно-справочных.
+
Список карточек _ДокументДП -- Информационно-справочный_, удовлетворяющих следующим критериям параметрического поиска:
+
* Состояние.
* Статус.
* Числовая часть временного регистрационного номера (интервал).
* Числовая часть постоянного регистрационного номера (интервал).
* Название.
* Автор.
* Подразделение.
* Дата регистрации (интервал).
* Подготовил.
* Индекс дела (интервал).
* Получатели (сотрудники).
* Признак контроля.
+
. Проекты информационно-справочных.
+
Незарегистрированные информационно-справочные документы и все их дочерние документы.
