= Папки для работы с отчетами

Для работы с отчетами в приложении "{ow}" предназначена группа папок `Отчеты`, доступная всем пользователям. Папки данной группы предназначены для отображения сведений о работе пользователя. В стандартной поставке Приложения настроено использование отчетов `Исполнение документов`, `Исполнение резолюций` и `Исполнение заданий`.

. Исполнение документов.
+
Список карточек _ДокументДП_ в состоянии `На рассмотрении`, `Зарегистрирован`, `На исполнении`, удовлетворяющих следующим критериям параметрического поиска:
+
* Период, в который был зарегистрирован документ.
* Автор.
* Вид документа.
* Подразделение.
+
. Исполнение заданий.
+
Список незавершенных заданий, удовлетворяющих следующим критериям параметрического поиска:
+
* Исполнитель.
* Подразделение исполнителя.
* Вид задания.
* Срок исполнения.
+
. Исполнение резолюций.
+
Список карточек _Резолюция_ в состоянии `На исполнении`, удовлетворяющих следующим критериям параметрического поиска:
+
* Период, в который была создана Резолюция.
* Автор.
* Подразделение.
