= Папки для работы с распорядительными документами

Папка Распорядительные предназначена для создания карточек _ДокументДП -- Распорядительный_ и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек _ДокументДП -- Распорядительный_ в различных состояниях по различным атрибутам.

. Архив распорядительных Распорядительные документы и все их дочерние документы в состоянии `В архиве`
. Журнал распорядительных Распорядительные документы и все их дочерние документы, зарегистрированные в текущем году.
. Поиск распорядительных Список карточек _ДокументДП -- Распорядительный_, удовлетворяющих следующим критериям параметрического поиска:
+
* Состояние.
* Статус.
* Числовая часть временного регистрационного номера (интервал).
* Числовая часть постоянного регистрационного номера (интервал).
* Название.
* Автор.
* Подразделение.
* Дата регистрации, интервал.
* Подготовил, можно задать несколько.
* Индекс дела, интервал.
* Получатели, сотрудники, можно задать несколько.
* Признак контроля.
+
. Проекты распорядительных.
+
Незарегистрированные распорядительные документы и все их дочерние документы.
+
. Распорядительные на исполнении.
+
Распорядительные документы и все их дочерние документы в состоянии `На исполнении`.
+
. Распорядительные на рассмотрении.
+
Распорядительные документы и все их дочерние документы в состоянии `На рассмотрении`.
