= Папки для работы с распорядительными документами

Папка Распорядительные предназначена для создания карточек ДокументДП-Распорядительный и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек ДокументДП-Распорядительный в различных состояниях по различным атрибутам.

. Архив распорядительных Распорядительные документы и все их дочерние документы в состоянии "В архиве"
. Журнал распорядительных Распорядительные документы и все их дочерние документы, зарегистрированные в текущем году
. Поиск распорядительных Список карточек ДокументДП -- Распорядительный, удовлетворяющих следующим критериям параметрического поиска:
* состояние;
* статус;
* числовая часть временного регистрационного номера (интервал);
* числовая часть постоянного регистрационного номера (интервал);
* название;
* автор;
* подразделение;
* дата регистрации (интервал);
* подготовил (можно задать несколько);
* индекс дела (интервал);
* получатели (сотрудники) (можно задать несколько);
* признак контроля.
. Проекты распорядительных.
+
Незарегистрированные распорядительные документы и все их дочерние документы.
. Распорядительные на исполнении.
+
Распорядительные документы и все их дочерние документы в состоянии "На исполнении".
. Распорядительные на рассмотрении.
+
Распорядительные документы и все их дочерние документы в состоянии "На рассмотрении".
