= Папки для работы с входящими документами

Папка `Входящие` предназначена для создания карточек _ДокументДП_ -- Входящий и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек _ДокументДП_ -- Входящий в различных состояниях по различным атрибутам.

. Архив входящих.
+
Входящие документы и все их дочерние документы в состоянии _В архиве_
+
. Входящие на исполнении.
+
Входящие документы и все их дочерние документы в состоянии _На исполнении_.
+
. Входящие на рассмотрении.
+
Входящие документы и все их дочерние документы в состоянии _На рассмотрении_.
+
. Журнал входящих _Входящие_ документы и все их дочерние документы, зарегистрированные в текущем году
. Поиск входящих.
+
Список карточек _ДокументДП -- Входящий_, удовлетворяющих следующим критериям параметрического поиска:
+
* Состояние.
* Числовая часть постоянного регистрационного номера (интервал).
* Название.
* Организация-отправитель.
* Дата регистрации (интервал).
* Регистратор входящих.
* Получатели (сотрудники).
* Подразделение.
* Признак контроля.
