= Папки для работы с информационно-справочными документами

Папка `Информационно-справочные` предназначена для создания карточек ДокументДП - Информационно-справочный и работы с ними.

Папка содержит вложенную структуру папок с настроенными поисковыми запросами, которая предназначена для поиска карточек ДокументДП - Информационно-справочный в различных состояниях по различным атрибутам.

[arabic]
. Архив информационно-справочных.
+
Информационно-справочные документы и все их дочерние документы в состоянии "В архиве".
. Журнал информационно-справочных.
. Информационно-справочные документы и все их дочерние документы, зарегистрированные в текущем году.
. Информационно-справочные на исполнении.
+
Информационно-справочные документы и все их дочерние документы в состоянии "На исполнении".
. Информационно-справочные на рассмотрении.
+
Информационно-справочные документы и все их дочерние документы в состоянии "На рассмотрении".
. Поиск информационно-справочных.
+
Список карточек ДокументДП - Информационно-справочный, удовлетворяющих следующим критериям параметрического поиска:
* состояние;
* статус;
* числовая часть временного регистрационного номера (интервал);
* числовая часть постоянного регистрационного номера (интервал);
* название;
* автор;
* подразделение;
* дата регистрации (интервал);
* подготовил;
* индекс дела (интервал);
* получатели (сотрудники);
* признак контроля.
. Проекты информационно-справочных.
+
Незарегистрированные информационно-справочные документы и все их дочерние документы
