= Папки для работы с отчетами

Для работы с отчетами в приложении "Делопроизводство. Версия 5" предназначена группа папок `Отчеты`, доступная всем пользователям. Папки данной группы предназначены для отображения сведений о работе пользователя. В стандартной поставке Приложения настроено использование отчетов "Исполнение документов", "Исполнение резолюций" и "Исполнение заданий".

. Исполнение документов.
+
Список карточек ДокументДП в состоянии "На рассмотрении", "Зарегистрирован", "На исполнении", удовлетворяющих следующим критериям параметрического поиска:
* период, в который был зарегистрирован документ;
* автор;
* вид документа;
* подразделение.
. Исполнение заданий.
+
Список незавершенных заданий, удовлетворяющих следующим критериям параметрического поиска:
* исполнитель;
* подразделение исполнителя;
* вид задания;
* срок исполнения.
. Исполнение резолюций.
+
Список карточек Резолюция в состоянии "На исполнении", удовлетворяющих следующим критериям параметрического поиска:
* период, в который была создана Резолюция;
* автор;
* подразделение.
