= Добавление отчетов, комментариев, документов во исполнение

При работе с заданиями предусмотрены следующие возможности фиксации хода исполнения задания: добавление комментариев, добавление отчётов об исполнении, добавление документов во исполнение.

____
Документы во исполнение отображаются в дереве резолюций (и могут быть открыты из дерева), могут быть скопированы в родительское задание.

Отчеты в дереве резолюций не отображаются.
____

[arabic]
. Для добавления комментария к заданию нажмите кнопку *Добавить* на ленте инструментов карточки задания По резолюции, либо выберите одноимённый пункт контекстного меню, открываемого в поле ввода комментариев на вкладке Отчеты и комментарии.
. В качестве отчета об исполнении задания можно добавить текстовый отчет, прикрепить ссылку на карточку отчета.
[arabic]
.. Для добавления текстового отчёта введите его текст в поле Отчеты на вкладке Отчеты и комментарии.
.. Файлы и документы отчета добавляются в поле Файлы отчетов на вкладке Отчеты и комментарии.
. Для добавления документа во исполнение нажмите на ленте инструментов карточки задания По резолюции кнопку *Создать*, *Добавить* или *Копировать все* из группы Документ во исполнение.
