= Рассмотрение документа должностным лицом, не работающим в СЭД

Если должностное лицо не работает с {dv} (то есть работает только с бумажными документами), то рассмотрение документа проходит c участием "помощника" назначенного исполнителя по описанному ниже сценарию.

____
Помощник – сотрудник, указанный в Справочнике сотрудников как постоянный заместитель исполнителя. Наличие помощника регулируется регламентом организации.
____

[arabic]
. Помощник, работающий в СЭД, xref:Task_Take_Consideration.adoc[получает задание] На рассмотрение в папку маршрутизации Я - помощник. Задания без подчиненной резолюции.
. Помощник xref:Print_Resolution_Blank.adoc[распечатывает бланк резолюции]. В бланке указаны автор, наименование документа, дата и регистрационный номер документа.
. Помощник заполняет необходимые поля распечатанного бланка ("Кому", "Текст поручения" и пр.) и передает его исполнителю вместе с распечатанными файлами рассматриваемого документа.
. Исполнитель знакомится с файлами документа, заполняет бланк резолюции и возвращает его помощнику.
. Исходя из ответа исполнителя помощник выполняет одно из действий с заданием На рассмотрение:
* xref:Creat_Resolution.adoc[создает карточку Резолюция] и xref:Schedule_Resolution.adoc[заполняет ее поля] согласно бланку;
* xref:Task_Delegate.adoc[делегирует задание];
* xref:Task_Finish.adoc[завершает задание];
* xref:Task_Reject.adoc[отклоняет задание].
