= Создание и управление резолюцией

Резолюция служит для формирования заданий исполнителям, их рассылки и контроля исполнения.

Резолюция может содержать несколько пунктов. Каждый пункт позволяет создавать детализированные распоряжения, предназначенные для выполнения сразу несколькими исполнителями. В качестве исполнителя может быть выбран сотрудник (или несколько сотрудников), подразделения, группы или роли из Справочника сотрудников.

Для каждого исполнителя в пункте создается своё задание. Все задания по резолюции рассылаются одновременно в момент xref:Sent_Resolution_for_Execution.adoc[отправки резолюции на исполнение]. Если в качестве исполнителя выбрано подразделение, группа или роль, задания будут разосланы всем приписанным к ним сотрудникам.

____
Один сотрудник может быть исполнителем нескольких заданий пункта резолюции. Например, если пользователь был явно выбран как исполнитель одного из заданий пункта и входит в группу исполнителей другого задания пункта, то он получит две карточки задания.

Явно выбрать сотрудника исполнителем двух заданий одного пункта резолюции нельзя.
____

Один из исполнителей пункта резолюции может быть назначен ответственным; он может завершить задания остальных исполнителей своего пункта резолюции. Ответственные исполнители могут быть назначены для каждого пункта резолюции.

Для контроля исполнения пунктов резолюции предусмотрены два вида приемки (контроль организации и контроль подразделения) и/или xref:Task_Fulfil_Progress.adoc[контроль хода исполнения заданий] пункта резолюции. Приемке подлежит задание ответственного исполнителя пункта (если он назначен) или всех исполнителей пункта (если ответственный исполнитель не назначен).
