= Рекомендации по внесению изменений в Приложение

Далее по тексту используются следующие понятия:

* _Стандартный вид_ -- вид карточки, включенный в поставку Приложения.
* _Дочерний вид_ -- вид карточки, добавленный как подчиненный, к виду карточки, включенному в поставку Приложения.

Ниже приведены рекомендации по внесению изменений в настройки Приложения, которые допускается изменять.

. Изменение настройки правила нумерации.
+
Разрешено выполнять в стандартных видах карточек.
. Добавление записей в Конструктор справочников: место регистрации, сроки хранения, статус документа, типы доставки, контроль, виды приёмки, гриф.
+
Выполняется стандартным образом.
. Добавление записей в группы Справочник сотрудников: Администратор номенклатуры дел, Контролёры организации.
+
Выполняется стандартным образом.
. Добавление нового вида карточки со стандартной логикой обработки.
+
В Справочнике видов карточек добавить в Дерево видов дочерние виды с полным наследованием от родительского вида.
. Исключение из использования стандартных видов карточек.
+
В Справочнике видов карточек установить флаг Не использовать при выборе.
+
После обновления флаг Не использовать при выборе необходимо установить повторно.
. Настройки в справочнике видов.
+
Следующие изменения допускается выполнять в стандартных видах карточек:
* добавление режимов создания;
* добавление файлов по умолчанию;
* добавление собственных преобразований для экспорта;
* добавление свойств для синхронизации;
* добавление атрибутов, включаемых в подпись, меток подписей.
+
Прочие изменения настроек Справочника видов карточек после обновления необходимо повторить.
+
Изменения настроек в дочерних видах можно выполнять без ограничений.
. Формирование дерева общих папок.
+
Папка `{ow}` и ее подпапки, кроме папки `Служебные`, при обновлении не меняются. Нужные папки можно использовать/перемещать в собственной структуре папок.
. Изменение папки `{ow}/Служебные` и её подпапок.
+
Данная структура может измениться при обновлении. При необходимости внесения изменений, можно скопировать нужные папки и вносить изменения в копии.
. Изменение стандартных фильтров и представлений.
+
Изменение и удаление фильтров и представлений Приложения запрещено. Можно настроить новые и подключить в дерево папок.
. Ролевая модель -- настройка Матрицы доступа.
+
Разрешено изменение Матрицы доступа для стандартных видов карточек.
. Ролевая модель -- добавление новой роли, изменение существующей роли.
+
Допускается добавление новой роли для стандартных видов карточек. Изменение и удаление ролей Приложения, включенных в поставку, разрешено только в дочерних видах.
. Изменение автомата состояний.
+
Разрешено выполнять только в дочерних видах.
+
Конструктор состояний содержит не включённые в автомат состояний состояния для карточек Документы ДП всех видов. Включение состояния осуществляется стандартным образом.
. Добавление поля в карточку.
+
Путём добавления динамического (расширенного) поля в карточку. Если поле необходимо вывести в разметке, требуется изменение разметки.
. Изменение разметки.
+
Изменение разметки для стандартных видов карточек Приложения запрещено. Для изменения разметки необходимо добавление дочернего вида карточки без использования наследования разметок.
. Изменение скриптов.
+
Изменение скриптов для стандартных видов карточек Приложения запрещено. Допускается изменение скриптов для добавленных дочерних видов (даже если все настройки наследуются) путем переопределения методов от родительского вида.
. Изменение маршрута согласования.
+
Разрешены изменения маршрута согласования в стандартных видах Приложения. Маршрут, настроенный согласно рекомендациям модуля "{dv} 5. Конструктор согласований", может быть подключен путем добавления соответствующего режима создания стандартной карточки согласования.
